# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 19:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instagram', '0003_auto_20180510_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='profile',
        ),
        migrations.AddField(
            model_name='photos',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
