# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0004_auto_20180510_2254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Photos',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
