# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-13 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0014_auto_20180513_0205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='image',
        ),
        migrations.AddField(
            model_name='photos',
            name='comments',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='instagram.Comments'),
            preserve_default=False,
        ),
    ]
