# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 13:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instagram', '0018_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='Photos_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
